/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
//import net.proteanit.sql.DbUtils;
//import DbUtils;

/**
 *
 * @author OSAMA
 */
public class CustomersList extends javax.swing.JPanel {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form CustomersList
     */
    public CustomersList() {
        initComponents();
        conn = JavaConnect.connectDb();
    }
    
    public void genTable() {
        try {
            String sql = "select * from Account";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            int i = 1;
            while(rs.next()) {
                String val1 = String.valueOf(i);
                String val2 = rs.getString("Name");
                String val3 = rs.getString("Acc");
                String val4 = rs.getString("Acc_Type");
                String val5 = rs.getString("Pin");
                String val6 = rs.getString("Phone");
                String val7 = rs.getString("Address");
                String val8 = rs.getString("Balance");
                String tbData[] = {val1,val2,val3,val4,val5,val6,val7,val8};
                DefaultTableModel tblModel = (DefaultTableModel) customersListTable.getModel();
                tblModel.addRow(tbData);
                i++;
            }
            TableColumnModel columnModel = customersListTable.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(25);
            columnModel.getColumn(1).setPreferredWidth(150);
            columnModel.getColumn(2).setPreferredWidth(55);
            columnModel.getColumn(3).setPreferredWidth(75);
            columnModel.getColumn(4).setPreferredWidth(25);
            columnModel.getColumn(5).setPreferredWidth(75);
            columnModel.getColumn(6).setPreferredWidth(150);
            columnModel.getColumn(7).setPreferredWidth(70);
//            customerListTable.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {}
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customersListTable = new javax.swing.JTable();

        customersListTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        customersListTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customersListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Name", "Account", "Account Type", "Pin", "Phone", "Address", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customersListTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable customersListTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
