/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author OSAMA
 */
public class Deposit extends javax.swing.JPanel {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form Deposit
     */
    public Deposit() {
        initComponents();
        conn = JavaConnect.connectDb();
    }
    
    public void getDetails(String accNo) {
        String sql = "select * from Account where Acc=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, accNo);
            rs = pst.executeQuery();
            if(rs.next()) {
                String add1 = rs.getString("Acc");
                accountNoTextField.setText(add1);
                String add2 = rs.getString("Name");
                nameTextField.setText(add2);
                String add3 = rs.getString("Balance");
                availableBalanceTextField.setText(add3);
                rs.close();
                pst.close();
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        } finally {
            try {
                rs.close();
                pst.close();
            } catch(Exception e) {}
        }
    }
    
    private void getTotalAmount() {
        if(depositAmountTextField.getText().equalsIgnoreCase("") || Integer.parseInt(depositAmountTextField.getText())==0) {
            totalTextField.setText("");
        }
        else {
            try {
                long availableBalance = Long.parseLong(availableBalanceTextField.getText());
                long depositAmount = Long.parseLong(depositAmountTextField.getText());
                long sum = availableBalance+depositAmount;
                String total = String.valueOf(sum);
                totalTextField.setText(total);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountNoLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        availableBalanceLabel = new javax.swing.JLabel();
        depositAmountLabel = new javax.swing.JLabel();
        totalButton = new javax.swing.JButton();
        depositButton = new javax.swing.JButton();
        accountNoTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        availableBalanceTextField = new javax.swing.JTextField();
        depositAmountTextField = new javax.swing.JTextField();
        totalTextField = new javax.swing.JTextField();

        accountNoLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        accountNoLabel.setText("Account No.");

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nameLabel.setText("Name");

        availableBalanceLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        availableBalanceLabel.setText("Available Balance");

        depositAmountLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        depositAmountLabel.setText("Deposit Amount");

        totalButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        totalButton.setText("Total");
        totalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalButtonActionPerformed(evt);
            }
        });

        depositButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        accountNoTextField.setEditable(false);
        accountNoTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        nameTextField.setEditable(false);
        nameTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        availableBalanceTextField.setEditable(false);
        availableBalanceTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        depositAmountTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        totalTextField.setEditable(false);
        totalTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(accountNoLabel)
                                .addGap(74, 74, 74)
                                .addComponent(accountNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availableBalanceLabel)
                                    .addComponent(depositAmountLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(depositAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(availableBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(totalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNoLabel)
                    .addComponent(accountNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availableBalanceLabel)
                    .addComponent(availableBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositAmountLabel)
                    .addComponent(depositAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalButton))
                .addGap(18, 18, 18)
                .addComponent(depositButton)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void totalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalButtonActionPerformed
        // TODO add your handling code here:
        getTotalAmount();
    }//GEN-LAST:event_totalButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
        getTotalAmount();
        if(depositAmountTextField.getText().equalsIgnoreCase("") || Integer.parseInt(depositAmountTextField.getText())==0) {
            totalTextField.setText("");
        }
        else {
            try {
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
                LocalDateTime now = LocalDateTime.now();
                String dateTime = dtf.format(now);
                String val1 = "Human";
                String val2 = accountNoTextField.getText();
                String val3 = depositAmountTextField.getText();
                String val4 = totalTextField.getText();
                String sql = "insert into BalancesHistory(Sender,Receiver,Amount,Timestamp) values (?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, val1);
                pst.setString(2, val2);
                pst.setString(3, val3);
                pst.setString(4, dateTime);
                pst.execute();
                pst.close();
                sql = "update Account set Balance='"+val4+"' where Acc='"+val2+"'";
                pst = conn.prepareStatement(sql);
                pst.execute();
                pst.close();
                JOptionPane.showMessageDialog(null, "Deposited Successfully!");
                getDetails(val2);
                depositAmountTextField.setText("");
                totalTextField.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                e.printStackTrace();
            } finally {
                try {
                    pst.close();
                } catch (Exception e) {}
            }
        }
    }//GEN-LAST:event_depositButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNoLabel;
    private javax.swing.JTextField accountNoTextField;
    private javax.swing.JLabel availableBalanceLabel;
    private javax.swing.JTextField availableBalanceTextField;
    private javax.swing.JLabel depositAmountLabel;
    private javax.swing.JTextField depositAmountTextField;
    private javax.swing.JButton depositButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton totalButton;
    private javax.swing.JTextField totalTextField;
    // End of variables declaration//GEN-END:variables
}
