/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author OSAMA
 */
public class Profile extends javax.swing.JPanel {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
        conn = JavaConnect.connectDb();
    }
    
    public void getDetails(String accNo) {
        String sql = "select * from Account where Acc=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, accNo);
            rs = pst.executeQuery();
            if(rs.next()) {
                String add1 = rs.getString("Name");
                nameTextField.setText(add1);
                String add2 = rs.getString("DOB");
                dateOfBirthTextField.setText(add2);
                String add3 = rs.getString("Gender");
                genderTextField.setText(add3);
                String add4 = rs.getString("Religion");
                religionTextField.setText(add4);
                String add5 = rs.getString("Phone");
                phoneTextField.setText(add5);
                String add6 = rs.getString("Acc");
                accountNoTextField.setText(add6);
                String add7 = rs.getString("Acc_Type");
                accountTypeTextField.setText(add7);
                String add8 = rs.getString("Sec_Q");
                securityQTextField.setText(add8);
                String add9 = rs.getString("Address");
                addressTextField.setText(add9);
                String add10 = rs.getString("Balance");
                balanceTextField.setText(add10);
                rs.close();
                pst.close();
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        } finally {
            try {
                rs.close();
                pst.close();
            } catch(Exception e) {
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        dateOfBirthLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        religionLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        accountNoLabel = new javax.swing.JLabel();
        accountTypeLabel = new javax.swing.JLabel();
        securityQLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        dateOfBirthTextField = new javax.swing.JTextField();
        genderTextField = new javax.swing.JTextField();
        religionTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        accountNoTextField = new javax.swing.JTextField();
        accountTypeTextField = new javax.swing.JTextField();
        securityQTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        balanceLabel = new javax.swing.JLabel();
        balanceTextField = new javax.swing.JTextField();

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nameLabel.setText("Name");

        dateOfBirthLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        dateOfBirthLabel.setText("Date Of Birth");

        genderLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        genderLabel.setText("Gender");

        religionLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        religionLabel.setText("Religion");

        phoneLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        phoneLabel.setText("Phone");

        accountNoLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        accountNoLabel.setText("Account No.");

        accountTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        accountTypeLabel.setText("Account Type");

        securityQLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        securityQLabel.setText("Security Q.");

        addressLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addressLabel.setText("Address");

        nameTextField.setEditable(false);
        nameTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        dateOfBirthTextField.setEditable(false);
        dateOfBirthTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        genderTextField.setEditable(false);
        genderTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        religionTextField.setEditable(false);
        religionTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        phoneTextField.setEditable(false);
        phoneTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        accountNoTextField.setEditable(false);
        accountNoTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        accountTypeTextField.setEditable(false);
        accountTypeTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        securityQTextField.setEditable(false);
        securityQTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        addressTextField.setEditable(false);
        addressTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        editButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        balanceLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        balanceLabel.setText("Balance");

        balanceTextField.setEditable(false);
        balanceTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneLabel)
                            .addComponent(dateOfBirthLabel)
                            .addComponent(genderLabel)
                            .addComponent(religionLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateOfBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(religionTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(genderTextField)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(81, 81, 81)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountNoLabel)
                    .addComponent(accountTypeLabel)
                    .addComponent(securityQLabel)
                    .addComponent(addressLabel)
                    .addComponent(balanceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressTextField)
                    .addComponent(securityQTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accountTypeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accountNoTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(balanceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accountNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accountNoLabel))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateOfBirthLabel)
                            .addComponent(dateOfBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accountTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accountTypeLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderLabel)
                            .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(securityQLabel)
                            .addComponent(securityQTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(religionLabel)
                            .addComponent(religionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressLabel))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabel)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balanceLabel))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(saveButton))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        nameTextField.setEditable(true);
        dateOfBirthTextField.setEditable(true);
        genderTextField.setEditable(true);
        religionTextField.setEditable(true);
        phoneTextField.setEditable(true);
        addressTextField.setEditable(true);
        saveButton.setEnabled(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try {
            String val1 = nameTextField.getText();
            String val2 = dateOfBirthTextField.getText();
            String val3 = genderTextField.getText();
            String val4 = religionTextField.getText();
            String val5 = phoneTextField.getText();
            String val6 = addressTextField.getText();
            String val7 = accountNoTextField.getText();
            String sql = "update Account set Name='"+val1+"',DOB='"+val2+"',Gender='"+val3+"',Religion='"+val4+"',Phone='"+val5+"',Address='"+val6+"' where Acc='"+val7+"'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Profile Updated!");
            nameTextField.setEditable(false);
            dateOfBirthTextField.setEditable(false);
            genderTextField.setEditable(false);
            religionTextField.setEditable(false);
            phoneTextField.setEditable(false);
            addressTextField.setEditable(false);
            saveButton.setEnabled(false);
//            saveButton.disable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNoLabel;
    public javax.swing.JTextField accountNoTextField;
    private javax.swing.JLabel accountTypeLabel;
    public javax.swing.JTextField accountTypeTextField;
    private javax.swing.JLabel addressLabel;
    public javax.swing.JTextField addressTextField;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JTextField balanceTextField;
    private javax.swing.JLabel dateOfBirthLabel;
    public javax.swing.JTextField dateOfBirthTextField;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel genderLabel;
    public javax.swing.JTextField genderTextField;
    private javax.swing.JLabel nameLabel;
    public javax.swing.JTextField nameTextField;
    private javax.swing.JLabel phoneLabel;
    public javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel religionLabel;
    public javax.swing.JTextField religionTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel securityQLabel;
    public javax.swing.JTextField securityQTextField;
    // End of variables declaration//GEN-END:variables
}
