/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author OSAMA
 */
public class Transactions extends javax.swing.JPanel {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    
//    String val = "6799";
//    String sqlForGettingTransactions = "select * from BalancesHistory where Sender='"+val+"' or Receiver='"+val+"'";

    /**
     * Creates new form Transactions
     */
    public Transactions() {
        initComponents();
        conn = JavaConnect.connectDb();
    }
    
    public void genTable(String sql) {
        try {
//            String sql = "select * from BalancesHistory";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            int i = 1;
            while(rs.next()) {
                String val1 = String.valueOf(i);
                String val2 = rs.getString("Sender");
                String val3 = rs.getString("Receiver");
                String val4 = rs.getString("Amount");
                String val5 = rs.getString("Timestamp");
//                String val5 = rs.getString("Phone");
//                String val6 = rs.getString("Address");
//                String val7 = rs.getString("Balance");
                String tbData[] = {val1,val2,val3,val4,val5};
                DefaultTableModel tblModel = (DefaultTableModel) transactionsTable.getModel();
                tblModel.addRow(tbData);
                i++;
            }
            TableColumnModel columnModel = transactionsTable.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(25);
            columnModel.getColumn(1).setPreferredWidth(75);
            columnModel.getColumn(2).setPreferredWidth(75);
            columnModel.getColumn(3).setPreferredWidth(75);
            columnModel.getColumn(4).setPreferredWidth(100);
//            columnModel.getColumn(5).setPreferredWidth(150);
//            columnModel.getColumn(6).setPreferredWidth(75);
//            customerListTable.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {}
        }
    }
    
    public void removeAllRowsOfTable() {
        transactionsTable.setModel(new DefaultTableModel(null, new String[] {"S.No.","Sender","Receiver","Amount","Date & Time"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        transactionsTable = new javax.swing.JTable();

        transactionsTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        transactionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Sender", "Receiver", "Amount", "Date & Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(transactionsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable transactionsTable;
    // End of variables declaration//GEN-END:variables
}
